### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by VonOx**

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Let me know if at some point I need to redeploy a build on Gladys website :)

**Comment by VonOx** [comment]
Yes you can , I've already build one => https://github.com/GladysAssistant/gladys-pi-gen/releases/tag/v0.1.2

Previous version is 5 months old now, so it's ok to push some packages update :)

Thank you

**Comment by Pierre-Gilles** [comment]
Did you test the final build on a real Raspberry Pi ? :) 

Thanks for making the update!

**Comment by VonOx** [comment]
I just ran a qemu test in local, no free SD card on my side to test on pi HW. But commit in upstream concern build itself, so risk is low.

**Comment by Pierre-Gilles** [comment]
I'll do a real life test before pushing, risk is low but in IT we never know and I don't want to push something without testing :)

**Comment by VonOx** [comment]
Yes do it if you have pi to test thanks

**Comment by Pierre-Gilles** [comment]
As your GPIO tests are a success, maybe I'll test both at the same time ? Or do you plan to release the GPIO thing later?

**Comment by VonOx** [comment]
We can merge gpio branch, nothing really fancy because ports are just exposed in containers ( I've tested gpio without lib, shell only). But I need to update documentation too if we release

**Comment by Pierre-Gilles** [comment]
Ok! Can you merge GPIO then and restart a build ? I'll retest the build with all those changes

**Pull request merged**
