### PR TITLE
Add GPIO capabilities to Gladys container

### PR DESCRIPTION
**Pull request by VonOx**
Need to test and update the documentation too

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Did you test this ? :)

**Comment by VonOx** [comment]
I will. Need to install docker on my pi3.

**Comment by VonOx** [comment]
Successful test, gpio ports are available inside container.

**Comment by Pierre-Gilles** [comment]
Nice !! :)

**Comment by VonOx** [comment]
Suggested lib for futur integration

https://github.com/fivdi/onoff#how-does-onoff-work

**Pull request merged**
